[build]
  command = "dotnet publish -c Release"
  publish = "bin/Release/net8.0/publish/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = true
  css.bundle = false
  js.bundle = false
  html.pretty_urls = false
